DROP TABLE IF EXISTS videos;
 
CREATE TABLE videos (
  id INT AUTO_INCREMENT  PRIMARY KEY,
  videoId VARCHAR(250) NOT NULL,
  title VARCHAR NOT NULL,
  categoryCode VARCHAR(250) NOT NULL,
  thumbnailUrl VARCHAR DEFAULT NULL
);